const NUMBER_ARTICLES_FOR_DISPLAY_DEFAULT = 3;
const NUMBER_ARTICLES_FOR_DISPLAY_FOR_TWO_COLUMNS = 2;
const NUMBER_ARTICLES_FOR_DISPLAY = 3;
const EMAIL_PATTERN = '^([a-zA-Z0-9\\-_]+(\\.[a-zA-Z0-9\\-_]+)*)@(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])\\.)+[a-zA-Z]{2,6}$';

export {
  NUMBER_ARTICLES_FOR_DISPLAY,
  NUMBER_ARTICLES_FOR_DISPLAY_DEFAULT,
  NUMBER_ARTICLES_FOR_DISPLAY_FOR_TWO_COLUMNS,
  EMAIL_PATTERN,
};
