const NUMBER_ARTICLES_FOR_DISPLAY_DEFAULT = 3;
const NUMBER_ARTICLES_FOR_DISPLAY_FOR_TWO_COLUMNS = 2;
const NUMBER_ARTICLES_FOR_DISPLAY = 3;

export {
  NUMBER_ARTICLES_FOR_DISPLAY,
  NUMBER_ARTICLES_FOR_DISPLAY_DEFAULT,
  NUMBER_ARTICLES_FOR_DISPLAY_FOR_TWO_COLUMNS,
};
